global:
 scrape_interval: 15s

scrape_configs:
 - job_name: 'node'
   static_configs:
     - targets:
       - 'p_nodeexp:9100'
       labels:
         group: 'docker-host'
 - job_name: 'docker-container'
   static_configs:
     - targets:
       - 'cadvisor:8080'
       labels:
         group: 'docker-container'

